// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type FindLatestCompletionReq struct {
	Limit  int32 `form:"limit,range=[10:20],default=10"`
	Offset int32 `form:"offset,range=[0:100],default=0"`
}

type FindLatestCompletionResp struct {
}

type FindLatestWrReq struct {
	Limit  int32 `form:"limit,range=[10:20],default=10"`
	Offset int32 `form:"offset,range=[0:100],default=0"`
}

type FindLatestWrResp struct {
}

type FindTopPointPlayerReq struct {
	Limit  int32 `form:"limit,range=[10:20],default=10"`
	Offset int32 `form:"offset,range=[0:100],default=0"`
}

type FindTopPointPlayerResp struct {
}
