// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"ShavitBhopWeb/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsAllMiddleware, serverCtx.PublicAccessFilter},
			[]rest.Route{
				{
					// 最近完成
					Method:  http.MethodGet,
					Path:    "/latest/completion",
					Handler: FindLatestCompletionHandler(serverCtx),
				},
				{
					// 最近WR
					Method:  http.MethodGet,
					Path:    "/latest/wr",
					Handler: FindLatestWrHandler(serverCtx),
				},
				{
					// 最高分玩家
					Method:  http.MethodGet,
					Path:    "/top/point",
					Handler: FindTopPointPlayerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
