// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"database/sql"
)

type Chat struct {
	Auth      int32          `json:"auth"`
	Name      int32          `json:"name"`
	Ccname    sql.NullString `json:"ccname"`
	Message   int32          `json:"message"`
	Ccmessage sql.NullString `json:"ccmessage"`
	Ccaccess  int32          `json:"ccaccess"`
}

type DuplicateSameTime struct {
	ID           int32           `json:"id"`
	Style        int8            `json:"style"`
	Track        int8            `json:"track"`
	Time         float64         `json:"time"`
	Auth         sql.NullInt32   `json:"auth"`
	Map          string          `json:"map"`
	Points       float64         `json:"points"`
	ExactTimeInt sql.NullInt32   `json:"exactTimeInt"`
	Jumps        sql.NullInt32   `json:"jumps"`
	Date         sql.NullInt32   `json:"date"`
	Strafes      sql.NullInt32   `json:"strafes"`
	Sync         sql.NullFloat64 `json:"sync"`
	Perfs        sql.NullFloat64 `json:"perfs"`
	Completions  sql.NullInt16   `json:"completions"`
}

type DuplicateTimeDetail struct {
	ID           int32           `json:"id"`
	Style        int8            `json:"style"`
	Track        int8            `json:"track"`
	Time         float64         `json:"time"`
	Auth         sql.NullInt32   `json:"auth"`
	Map          string          `json:"map"`
	Points       float64         `json:"points"`
	ExactTimeInt sql.NullInt32   `json:"exactTimeInt"`
	Jumps        sql.NullInt32   `json:"jumps"`
	Date         sql.NullInt32   `json:"date"`
	Strafes      sql.NullInt32   `json:"strafes"`
	Sync         sql.NullFloat64 `json:"sync"`
	Perfs        sql.NullFloat64 `json:"perfs"`
	Completions  sql.NullInt16   `json:"completions"`
}

type DuplicatedTime struct {
	Style int8          `json:"style"`
	Track int8          `json:"track"`
	Auth  sql.NullInt32 `json:"auth"`
	Map   string        `json:"map"`
}

type Maptier struct {
	Map  string `json:"map"`
	Tier int32  `json:"tier"`
}

type Mapzone struct {
	ID           int32           `json:"id"`
	Map          string          `json:"map"`
	Type         sql.NullInt32   `json:"type"`
	Corner1X     sql.NullFloat64 `json:"corner1X"`
	Corner1Y     sql.NullFloat64 `json:"corner1Y"`
	Corner1Z     sql.NullFloat64 `json:"corner1Z"`
	Corner2X     sql.NullFloat64 `json:"corner2X"`
	Corner2Y     sql.NullFloat64 `json:"corner2Y"`
	Corner2Z     sql.NullFloat64 `json:"corner2Z"`
	DestinationX float64         `json:"destinationX"`
	DestinationY float64         `json:"destinationY"`
	DestinationZ float64         `json:"destinationZ"`
	Track        int32           `json:"track"`
	Flags        int32           `json:"flags"`
	Data         int32           `json:"data"`
	Prebuilt     sql.NullBool    `json:"prebuilt"`
	Form         sql.NullInt16   `json:"form"`
	Target       sql.NullString  `json:"target"`
}

type Migration struct {
	Code int8 `json:"code"`
}

type Playertime struct {
	ID           int32           `json:"id"`
	Style        int8            `json:"style"`
	Track        int8            `json:"track"`
	Time         float64         `json:"time"`
	Auth         sql.NullInt32   `json:"auth"`
	Map          string          `json:"map"`
	Points       float64         `json:"points"`
	ExactTimeInt sql.NullInt32   `json:"exactTimeInt"`
	Jumps        sql.NullInt32   `json:"jumps"`
	Date         sql.NullInt32   `json:"date"`
	Strafes      sql.NullInt32   `json:"strafes"`
	Sync         sql.NullFloat64 `json:"sync"`
	Perfs        sql.NullFloat64 `json:"perfs"`
	Completions  sql.NullInt16   `json:"completions"`
}

type Stagetimespb struct {
	Style int8    `json:"style"`
	Track int8    `json:"track"`
	Map   string  `json:"map"`
	Stage int8    `json:"stage"`
	Auth  int32   `json:"auth"`
	Time  float64 `json:"time"`
}

type Stagetimeswr struct {
	Style int8    `json:"style"`
	Track int8    `json:"track"`
	Map   string  `json:"map"`
	Stage int8    `json:"stage"`
	Auth  int32   `json:"auth"`
	Time  float64 `json:"time"`
}

type Startposition struct {
	Auth       int32           `json:"auth"`
	Track      int8            `json:"track"`
	Map        string          `json:"map"`
	PosX       sql.NullFloat64 `json:"posX"`
	PosY       sql.NullFloat64 `json:"posY"`
	PosZ       sql.NullFloat64 `json:"posZ"`
	AngX       sql.NullFloat64 `json:"angX"`
	AngY       sql.NullFloat64 `json:"angY"`
	AngZ       sql.NullFloat64 `json:"angZ"`
	AnglesOnly sql.NullBool    `json:"anglesOnly"`
}

type Styleplaytime struct {
	Auth     int32   `json:"auth"`
	Style    int8    `json:"style"`
	Playtime float64 `json:"playtime"`
}

type User struct {
	Auth      int32          `json:"auth"`
	Name      sql.NullString `json:"name"`
	Ip        sql.NullInt32  `json:"ip"`
	Lastlogin int32          `json:"lastlogin"`
	Points    float64        `json:"points"`
	Playtime  float64        `json:"playtime"`
}

type Wr struct {
	ID           int32           `json:"id"`
	Style        int8            `json:"style"`
	Track        int8            `json:"track"`
	Time         float64         `json:"time"`
	Auth         sql.NullInt32   `json:"auth"`
	Map          string          `json:"map"`
	Points       float64         `json:"points"`
	ExactTimeInt sql.NullInt32   `json:"exactTimeInt"`
	Jumps        sql.NullInt32   `json:"jumps"`
	Date         sql.NullInt32   `json:"date"`
	Strafes      sql.NullInt32   `json:"strafes"`
	Sync         sql.NullFloat64 `json:"sync"`
	Perfs        sql.NullFloat64 `json:"perfs"`
	Completions  sql.NullInt16   `json:"completions"`
}

type Wrhrankall struct {
	Wrrank int32         `json:"wrrank"`
	Style  int32         `json:"style"`
	Auth   sql.NullInt32 `json:"auth"`
	Count  int64         `json:"count(*)"`
}

type Wrhrankbonu struct {
	Wrrank  int32         `json:"wrrank"`
	Style   int8          `json:"style"`
	Auth    sql.NullInt32 `json:"auth"`
	Wrcount int64         `json:"wrcount"`
}

type Wrhrankcvar struct {
	Wrrank int32         `json:"wrrank"`
	Style  int32         `json:"style"`
	Auth   sql.NullInt32 `json:"auth"`
	Count  int64         `json:"count(*)"`
}

type Wrhrankmain struct {
	Wrrank  int32         `json:"wrrank"`
	Style   int8          `json:"style"`
	Auth    sql.NullInt32 `json:"auth"`
	Wrcount int64         `json:"wrcount"`
}

type WrsMin struct {
	Time  sql.NullFloat64 `json:"time"`
	Map   string          `json:"map"`
	Track int8            `json:"track"`
	Style int8            `json:"style"`
}
